# Generated by Django 4.2.7 on 2024-11-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horsepower', models.IntegerField(default=0)),
                ('seatheight', models.IntegerField(default=0)),
                ('cylindercount', models.IntegerField(default=0)),
                ('displacement', models.IntegerField(default=0)),
                ('maximumtorque', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search_app.category')),
            ],
        ),
    ]
