# Generated by Django 4.2.13 on 2024-07-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
    ]
