# Generated by Django 4.2.13 on 2024-09-17 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='execution_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
