# Generated by Django 4.2.13 on 2024-09-17 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='execution_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
